name: deploy                    
on:                                  
  push:
    branches:
      - main
  
  workflow_dispatch:
  
jobs:                                
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code.   
        uses: actions/checkout@v3
      
      - name: Check Node v         
        run: node -v
        
      - name: Install dependencies   
        run: |
          cd frontend
          npm install


      - name: Inject environment variables
        run: |
          cd frontend
          cat <<EOF > .env
          VITE_BACKEND_URL=$VITE_BACKEND_URL
          VITE_SOCKET_URL=$VITE_SOCKET_URL
          VITE_FIREBASE_API_KEY=$VITE_FIREBASE_API_KEY
          VITE_FIREBASE_PROJECT_ID=$VITE_FIREBASE_PROJECT_ID
          VITE_FIREBASE_AUTH_DOMAIN=$VITE_FIREBASE_AUTH_DOMAIN
          VITE_FIREBASE_APP_ID=$VITE_FIREBASE_APP_ID
          VITE_FIREBASE_STORAGE_BUCKET=$VITE_FIREBASE_STORAGE_BUCKET
          VITE_FIREBASE_MESSAGING_SENDER_ID=$VITE_FIREBASE_MESSAGING_SENDER_ID
          VITE_FIREBASE_MEASUREMENT_ID=$VITE_FIREBASE_MEASUREMENT_ID
          VITE_FIREBASE_VAPID_KEY=$VITE_FIREBASE_VAPID_KEY
          EOF
        env:
          VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}
          VITE_SOCKET_URL: ${{ secrets.VITE_SOCKET_URL }}
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_APP_ID: $${{ secrets.VITE_FIREBASE_APP_ID}}
          VITE_FIREBASE_AUTH_DOMAIN: $${{ secrets.VITE_FIREBASE_AUTH_DOMAIN}}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }} 
          VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}
          VITE_FIREBASE_VAPID_KEY: ${{ secrets.VITE_FIREBASE_VAPID_KEY }}
          

      - name: Print .env file
        run: |
          cd frontend
          cat .env

      
      - name: Generate build        
        run:  |
          cd frontend
          ls -al
          CI=false npm run build
      
      - name: Deploy                
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd frontend
          aws s3 cp --recursive --region ap-northeast-2 dist s3://140pay.site
